# Generated by Django 3.1 on 2020-08-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('group_id', models.IntegerField(unique=True)),
                ('value', models.IntegerField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.PositiveIntegerField()),
                ('value_to_pay', models.FloatField()),
                ('sum_to_get', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('YA', 'Яндекс Деньги'), ('QI', 'Qiwi')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('been_success', models.BooleanField(default=False)),
                ('operation_id', models.CharField(max_length=255)),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField(max_length=2000)),
            ],
        ),
    ]
