# Generated by Django 2.1.7 on 2019-03-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTFMM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.PositiveIntegerField()),
                ('value_to_pay', models.PositiveIntegerField()),
                ('payment_type', models.CharField(choices=[('YA', 'Яндекс Деньги: Комиссия 0.5%')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('operation_id', models.CharField(max_length=255)),
            ],
        ),
    ]
