# Generated by Django 2.2.7 on 2019-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTFMM', '0010_auto_20190318_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='group_id',
            field=models.IntegerField(default=3281833, unique=True),
            preserve_default=False,
        ),
    ]
