# Generated by Django 2.2.7 on 2019-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTFMM', '0011_balance_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_id',
            field=models.IntegerField(default=3281833),
            preserve_default=False,
        ),
    ]
