# Generated by Django 2.1.7 on 2019-03-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTFMM', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value_to_pay',
            field=models.FloatField(),
        ),
    ]
