# Generated by Django 2.1.7 on 2019-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTFMM', '0003_auto_20190306_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum_to_get',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
