# Generated by Django 2.1.7 on 2019-03-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTFMM', '0004_order_sum_to_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='been_success',
            field=models.BooleanField(default=False),
        ),
    ]
