# Generated by Django 2.1.7 on 2019-03-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTFMM', '0007_auto_20190307_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('value', models.IntegerField()),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
