# Generated by Django 2.1.7 on 2019-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTFMM', '0008_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('YA', 'Яндекс Деньги: Комиссия 0.5%'), ('QI', 'QIWI: Комиссия 0%')], max_length=2),
        ),
    ]
