"""
Django settings for YTFMM project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm)75s41ps0mi!=q5!28t!()2-)s6qo8p(%ljrgb#u3%-1bt9%#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'YTFMM.apps.AppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'YTFMM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'YTFMM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

COOKIE = {
    '.ROBLOSECURITY': '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_CB80C5A876329A0FD3198365986FCB8382CB12A7E5B3EA33783AC674D8EA9087A32E559A0F41460C6DCBF7C46730D5531C943BDA24AB1DC64A8151DB398556ABF241E163A46A54FEE3FB3ECC0E41FD4C40ACF5489B8A6B6B322EAA599275757D713068035E8FAE8EE37BB4FEB664585F7767CD661DA4387814306DF1ED77706E6E741ED85C153C78CB7F84420D7B10AB2DD3B32C5BEF09D6F0BDFD1B165316AF5FA236AD22FBC5DF40415C5425AF0FF3E4BE6F383C2B3A84BC0B3BDDB8221A7A435E08A700CEDCC238D3925BFC28409F47C96B7FD345D54F09678913AAFE1367CA765D3775DE7B1A59623D1C4552A4B2A375DA9C40669E400FFD0289DCC74112E909C9FB07B45B0C6952CD16EB10678C09EC87BF75E68326C729A2E416C8D0A1586985F5',
}
GROUP_ID = '3281833'
GROUP_URL = 'https://www.roblox.com/groups/{}/search-members/{}'.format(GROUP_ID, '{}')
PREMIUM_ROLES = [254]
SEND_URL = 'https://www.roblox.com/groups/{}/one-time-payout/false'.format(GROUP_ID)
CSRF_URL = 'https://www.roblox.com/my/groupadmin.aspx?gid={}'.format(GROUP_ID)
JOIN_URL = 'https://www.roblox.com/groups/{}'.format(GROUP_ID)

DEFAULT_SETTINGS = {
    'percent': 0.5,
}
